version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/rhel/server:2019-latest
    environment:
      SA_PASSWORD: "someThingComplicated1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  link-application:
    image: link-application:v1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:sqlserver://db:1433;databaseName=linkapplication;encrypt=true;trustServerCertificate=true"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: "someThingComplicated1234"
    depends_on:
      - db
